/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.Views;

import java.awt.BorderLayout;
import static java.lang.String.format;
import static java.lang.String.format;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import main.dao.DocGiaDao;
import main.dao.DauSachDao;
import main.dao.ThongTinMuonTraDao;
import main.dao.NhaXuatBanDao;
import main.dao.TacGiaDao;
import main.dao.TheLoaiDao;
import main.dao.TuaSachDao;
import main.model.DocGia;
import main.model.TacGia;
import main.model.TheLoai;
import main.model.TuaSach;
import main.model.DauSach;
import main.model.NhaXuatBan;
import main.model.ThongTinMuonTra;

/**
 *
 * @author Admin
 */
public class NhaSanXuatVaTacGiaPanel extends javax.swing.JPanel {
    DefaultTableModel defaultTableModel1;
    DefaultTableModel defaultTableModel2;
    DefaultTableModel defaultTableModel3;
    DefaultTableModel defaultTableModel4;
    DefaultTableModel defaultTableModel5;
    DefaultTableModel defaultTableModel6;
    DefaultTableModel defaultTableModel7;
    DefaultTableModel defaultTableModel8;
    DefaultTableModel defaultTableModel9;
    DocGiaDao userDG;
    DauSachDao userDS;
    ThongTinMuonTraDao userTTMT;
    NhaXuatBanDao userNXB;
    TacGiaDao userTG;
    TheLoaiDao userTL;
    TuaSachDao userTS;
  SimpleDateFormat f= new SimpleDateFormat("MMMM dd, yyyy"); 
    /**
     * Creates new form NSX_TagiaJPanel
     */
    public NhaSanXuatVaTacGiaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btTracuu4_1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtTenNhaSX4 = new javax.swing.JTextField();
        btnXoa4 = new javax.swing.JButton();
        btnCapnhat4 = new javax.swing.JButton();
        btnThem4 = new javax.swing.JButton();
        btnLuu4 = new javax.swing.JButton();
        txtMaNXB4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblNhaSanXuat4 = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        btTracuu4_2 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtTenTacgia4 = new javax.swing.JTextField();
        btnXoa5 = new javax.swing.JButton();
        btnCapnhat5 = new javax.swing.JButton();
        btnThem5 = new javax.swing.JButton();
        btnLuu5 = new javax.swing.JButton();
        txtMaTacGia4 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblTacgia4 = new javax.swing.JTable();

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(0, 102, 153));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhà sản xuất"));

        btTracuu4_1.setBackground(new java.awt.Color(0, 102, 153));
        btTracuu4_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTracuu4_1.setForeground(new java.awt.Color(255, 255, 255));
        btTracuu4_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/seo (2).png"))); // NOI18N
        btTracuu4_1.setText("Tra cứu");
        btTracuu4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTracuu4_1ActionPerformed(evt);
            }
        });

        jLabel26.setText("Mã NSX:");

        jLabel27.setText("Tên nhà sản xuất:");

        btnXoa4.setBackground(new java.awt.Color(0, 102, 153));
        btnXoa4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa4.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/delete (2).png"))); // NOI18N
        btnXoa4.setText("Delete");
        btnXoa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa4ActionPerformed(evt);
            }
        });

        btnCapnhat4.setBackground(new java.awt.Color(0, 102, 153));
        btnCapnhat4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapnhat4.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/refresh (2).png"))); // NOI18N
        btnCapnhat4.setText("Refresh");
        btnCapnhat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhat4ActionPerformed(evt);
            }
        });

        btnThem4.setBackground(new java.awt.Color(0, 102, 153));
        btnThem4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem4.setForeground(new java.awt.Color(255, 255, 255));
        btnThem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/add-button (1).png"))); // NOI18N
        btnThem4.setText("Add");
        btnThem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem4ActionPerformed(evt);
            }
        });

        btnLuu4.setBackground(new java.awt.Color(0, 102, 153));
        btnLuu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu4.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/floppy-disk (1).png"))); // NOI18N
        btnLuu4.setText("Save");
        btnLuu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(txtMaNXB4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btTracuu4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTenNhaSX4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCapnhat4)
                            .addComponent(btnXoa4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThem4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLuu4))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btTracuu4_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaNXB4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtTenNhaSX4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu4)
                    .addComponent(btnXoa4))
                .addGap(47, 47, 47)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapnhat4)
                    .addComponent(btnThem4))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(tblNhaSanXuat4);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin tác giả"));

        btTracuu4_2.setBackground(new java.awt.Color(0, 102, 153));
        btTracuu4_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTracuu4_2.setForeground(new java.awt.Color(255, 255, 255));
        btTracuu4_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/seo (2).png"))); // NOI18N
        btTracuu4_2.setText("Tra cứu");
        btTracuu4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTracuu4_2ActionPerformed(evt);
            }
        });

        jLabel33.setText("Mã tác giả:");

        jLabel35.setText("Tên tác giả:");

        btnXoa5.setBackground(new java.awt.Color(0, 102, 153));
        btnXoa5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa5.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/delete (2).png"))); // NOI18N
        btnXoa5.setText("Delete");
        btnXoa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa5ActionPerformed(evt);
            }
        });

        btnCapnhat5.setBackground(new java.awt.Color(0, 102, 153));
        btnCapnhat5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapnhat5.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/refresh (2).png"))); // NOI18N
        btnCapnhat5.setText("Refresh");
        btnCapnhat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhat5ActionPerformed(evt);
            }
        });

        btnThem5.setBackground(new java.awt.Color(0, 102, 153));
        btnThem5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem5.setForeground(new java.awt.Color(255, 255, 255));
        btnThem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/add-button (1).png"))); // NOI18N
        btnThem5.setText("Add");
        btnThem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem5ActionPerformed(evt);
            }
        });

        btnLuu5.setBackground(new java.awt.Color(0, 102, 153));
        btnLuu5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu5.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/floppy-disk (1).png"))); // NOI18N
        btnLuu5.setText("Save");
        btnLuu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel35))
                .addGap(39, 39, 39)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(txtMaTacGia4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btTracuu4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTenTacgia4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapnhat5))
                .addGap(124, 124, 124)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu5))
                .addGap(106, 106, 106))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTracuu4_2)
                    .addComponent(txtMaTacGia4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtTenTacgia4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa5)
                    .addComponent(btnLuu5))
                .addGap(48, 48, 48)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapnhat5)
                    .addComponent(btnThem5))
                .addGap(40, 40, 40))
        );

        jScrollPane11.setViewportView(tblTacgia4);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1091, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btTracuu4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTracuu4_1ActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(this,"Vui lòng nhập tên Nhà xuất bản.",JOptionPane.INFORMATION_MESSAGE);

        defaultTableModel4.setRowCount(0);
        List<NhaXuatBan> user_NXB = userNXB.findByName(str);
        int sttnxb = 0;
        for (NhaXuatBan users : user_NXB) {
            sttnxb++;
            defaultTableModel4.addRow(new Object[]{sttnxb, users.getMaNXB(), users.getTenNXB()});
        }
        if (defaultTableModel4.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"Không tìm thấy","Thông báo", JOptionPane.ERROR_MESSAGE );
            List<NhaXuatBan> user_NXB2 = userNXB.getAll();
            int sttnxb2 = 0;
            for (NhaXuatBan users : user_NXB2) {
                sttnxb2++;
                defaultTableModel4.addRow(new Object[]{sttnxb2, users.getMaNXB(), users.getTenNXB()});
            }
        }
    }//GEN-LAST:event_btTracuu4_1ActionPerformed

    private void btnXoa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa4ActionPerformed
        // TODO add your handling code here:

        int row = tblNhaSanXuat4.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn Nhà xuất bản muốn xóa","Thông báo", JOptionPane.ERROR_MESSAGE );
        }else
        {
            int confident = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa Nhà xuất bản này hay không!");
            if (confident == JOptionPane.YES_OPTION) {
                String maNXB = String.valueOf(tblNhaSanXuat4.getValueAt(row, 1));
                userNXB.remove(maNXB);
                defaultTableModel4.removeRow(row);

            }
        }

    }//GEN-LAST:event_btnXoa4ActionPerformed

    private void btnCapnhat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhat4ActionPerformed
        // TODO add your handling code here:
        txtTenNhaSX4.setText("");
        txtMaNXB4.setText("");
        defaultTableModel4.setRowCount(0);
        List<NhaXuatBan> user_NXB = userNXB.getAll();
        int sttnxb=0;
        for(NhaXuatBan users : user_NXB){
            sttnxb++;
            defaultTableModel4.addRow(new Object[]{sttnxb,users.getMaNXB(),users.getTenNXB()});
        }
    }//GEN-LAST:event_btnCapnhat4ActionPerformed

    private void btnThem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem4ActionPerformed
        // TODO add your handling code here:
        NhaXuatBan nhaXuatBan = new NhaXuatBan();
        nhaXuatBan.setTenNXB(txtTenNhaSX4.getText());
        List<NhaXuatBan> list = new ArrayList<NhaXuatBan>();
        list.add(nhaXuatBan);
        userNXB.insert(nhaXuatBan);
    }//GEN-LAST:event_btnThem4ActionPerformed

    private void btnLuu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu4ActionPerformed
        // TODO add your handling code here:
        NhaXuatBan nhaXuatBan = new NhaXuatBan();
        nhaXuatBan.setMaNXB(txtMaNXB4.getText());
        nhaXuatBan.setTenNXB(txtTenNhaSX4.getText());
        List<NhaXuatBan> list = new ArrayList<NhaXuatBan>();
        list.add(nhaXuatBan);
        userNXB.update(nhaXuatBan);
    }//GEN-LAST:event_btnLuu4ActionPerformed

    private void btTracuu4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTracuu4_2ActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(this,"Vui lòng nhập tên Tác giả.",JOptionPane.INFORMATION_MESSAGE);

        defaultTableModel5.setRowCount(0);
        List<TacGia> user_TG = userTG.findByName(str);
        int stttg = 0;
        for (TacGia users : user_TG) {
            stttg++;
            defaultTableModel5.addRow(new Object[]{stttg, users.getMaTG(), users.getHoten()});
        }
        if (defaultTableModel5.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"Không tìm thấy","Thông báo", JOptionPane.ERROR_MESSAGE );
            List<TacGia> user_TG2 = userTG.getAll();
            int sttnxb2 = 0;
            for (TacGia users : user_TG2) {
                sttnxb2++;
                defaultTableModel5.addRow(new Object[]{sttnxb2, users.getMaTG(), users.getHoten()});
            }
        }
    }//GEN-LAST:event_btTracuu4_2ActionPerformed

    private void btnXoa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa5ActionPerformed
        // TODO add your handling code here:
        int row = tblTacgia4.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn Tác giá muốn xóa","Thông báo", JOptionPane.ERROR_MESSAGE );
        }else
        {
            int confident = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa Tác giả này hay không!");
            if (confident == JOptionPane.YES_OPTION) {
                String maTG = String.valueOf(tblTacgia4.getValueAt(row, 1));
                userTG.remove(maTG);
                defaultTableModel5.removeRow(row);
            }
        }
    }//GEN-LAST:event_btnXoa5ActionPerformed

    private void btnCapnhat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhat5ActionPerformed
        // TODO add your handling code here:
        txtMaTacGia4.setText("");
        txtTenTacgia4.setText("");
        defaultTableModel5.setRowCount(0);
        List<TacGia> user_TG = userTG.getAll();
        int stttg = 0;
        for(TacGia users: user_TG){
            stttg++;
            defaultTableModel5.addRow(new Object[]{stttg,users.getMaTG(),users.getHoten()});
        }
    }//GEN-LAST:event_btnCapnhat5ActionPerformed

    private void btnThem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem5ActionPerformed
        // TODO add your handling code here:
        TacGia tacGia = new TacGia();
        tacGia.setHoten(txtTenTacgia4.getText());
        List<TacGia> list = new ArrayList<TacGia>();
        list.add(tacGia);
        userTG.insert(tacGia);
    }//GEN-LAST:event_btnThem5ActionPerformed

    private void btnLuu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu5ActionPerformed
        // TODO add your handling code here:
        TacGia tacGia = new TacGia();
        tacGia.setMaTG(txtMaTacGia4.getText());
        tacGia.setHoten(txtTenTacgia4.getText());
        List<TacGia> list = new ArrayList<TacGia>();
        list.add(tacGia);
        userTG.update(tacGia);
    }//GEN-LAST:event_btnLuu5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTracuu4_1;
    private javax.swing.JButton btTracuu4_2;
    private javax.swing.JButton btnCapnhat4;
    private javax.swing.JButton btnCapnhat5;
    private javax.swing.JButton btnLuu4;
    private javax.swing.JButton btnLuu5;
    private javax.swing.JButton btnThem4;
    private javax.swing.JButton btnThem5;
    private javax.swing.JButton btnXoa4;
    private javax.swing.JButton btnXoa5;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblNhaSanXuat4;
    private javax.swing.JTable tblTacgia4;
    private javax.swing.JLabel txtMaNXB4;
    private javax.swing.JLabel txtMaTacGia4;
    private javax.swing.JTextField txtTenNhaSX4;
    private javax.swing.JTextField txtTenTacgia4;
    // End of variables declaration//GEN-END:variables
}
