/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.Views;
import java.awt.BorderLayout;
import static java.lang.String.format;
import static java.lang.String.format;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import main.dao.DocGiaDao;
import main.dao.DauSachDao;
import main.dao.ThongTinMuonTraDao;
import main.dao.NhaXuatBanDao;
import main.dao.TacGiaDao;
import main.dao.TheLoaiDao;
import main.dao.TuaSachDao;
import main.model.DocGia;
import main.model.TacGia;
import main.model.TheLoai;
import main.model.TuaSach;
import main.model.DauSach;
import main.model.NhaXuatBan;
import main.model.ThongTinMuonTra;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import main.dao.DauSachDao;
import main.dao.DocGiaDao;
import main.dao.NhaXuatBanDao;
import main.dao.TacGiaDao;
import main.dao.TheLoaiDao;
import main.dao.ThongTinMuonTraDao;
import main.dao.TuaSachDao;

/**
 *
 * @author Admin
 */
public class ThongTinMuonSachPanel extends javax.swing.JPanel {
    DefaultTableModel defaultTableModel1;
    DefaultTableModel defaultTableModel2;
    DefaultTableModel defaultTableModel3;
    DefaultTableModel defaultTableModel4;
    DefaultTableModel defaultTableModel5;
    DefaultTableModel defaultTableModel6;
    DefaultTableModel defaultTableModel7;
    DefaultTableModel defaultTableModel8;
    DefaultTableModel defaultTableModel9;
    DocGiaDao userDG;
    DauSachDao userDS;
    ThongTinMuonTraDao userTTMT;
    NhaXuatBanDao userNXB;
    TacGiaDao userTG;
    TheLoaiDao userTL;
    TuaSachDao userTS;
  SimpleDateFormat f= new SimpleDateFormat("MMMM dd, yyyy");
    /**
     * Creates new form Muon_traSachJPanel
     */
    public ThongTinMuonSachPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        CbbTenSach2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtSoluong2 = new javax.swing.JTextField();
        txtGhichu2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNgayMuon2 = new com.toedter.calendar.JDateChooser();
        txtNgayHenTra2 = new com.toedter.calendar.JDateChooser();
        txtNgayTra2 = new com.toedter.calendar.JDateChooser();
        txtMaMuon2 = new javax.swing.JLabel();
        txtMaDG2 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnXoa2 = new javax.swing.JButton();
        btnCapnhat2 = new javax.swing.JButton();
        btnThem2 = new javax.swing.JButton();
        btnLuu2 = new javax.swing.JButton();
        btTracuu2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMuontraSach2 = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(0, 102, 153));

        jPanel20.setBackground(new java.awt.Color(0, 102, 153));
        jPanel20.setForeground(new java.awt.Color(0, 102, 153));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin mượn trả"));

        jLabel16.setText("Mã mượn:");

        jLabel18.setText("Mã đọc giả");

        jLabel19.setText("Tên sách:");

        jLabel21.setText("Ngày mượn:");

        jLabel22.setText("Ngày hẹn trả:");

        CbbTenSach2.setBackground(new java.awt.Color(204, 255, 255));
        CbbTenSach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbTenSach2ActionPerformed(evt);
            }
        });

        jLabel20.setText("Số lượng:");

        jLabel23.setText("Ghi chú:");

        jLabel9.setText("Ngày trả:");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23)
                    .addComponent(jLabel20))
                .addGap(32, 32, 32)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(txtSoluong2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaMuon2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaDG2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CbbTenSach2, 0, 332, Short.MAX_VALUE)
                                    .addComponent(txtGhichu2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(txtNgayMuon2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayTra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNgayHenTra2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaMuon2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtMaDG2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbbTenSach2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGhichu2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayMuon2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayHenTra2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayTra2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtSoluong2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/library.png"))); // NOI18N

        btnXoa2.setBackground(new java.awt.Color(0, 102, 153));
        btnXoa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa2.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/delete (2).png"))); // NOI18N
        btnXoa2.setText("Delete");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });

        btnCapnhat2.setBackground(new java.awt.Color(0, 102, 153));
        btnCapnhat2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapnhat2.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/refresh (2).png"))); // NOI18N
        btnCapnhat2.setText("Refresh");
        btnCapnhat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhat2ActionPerformed(evt);
            }
        });

        btnThem2.setBackground(new java.awt.Color(0, 102, 153));
        btnThem2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem2.setForeground(new java.awt.Color(255, 255, 255));
        btnThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/add-button (1).png"))); // NOI18N
        btnThem2.setText("Add");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        btnLuu2.setBackground(new java.awt.Color(0, 102, 153));
        btnLuu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu2.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/floppy-disk (1).png"))); // NOI18N
        btnLuu2.setText("Save");
        btnLuu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu2ActionPerformed(evt);
            }
        });

        btTracuu2.setBackground(new java.awt.Color(0, 102, 153));
        btTracuu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTracuu2.setForeground(new java.awt.Color(255, 255, 255));
        btTracuu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/seo (2).png"))); // NOI18N
        btTracuu2.setText("Tra cứu");
        btTracuu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTracuu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCapnhat2))
                .addGap(22, 22, 22)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLuu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                        .addComponent(btTracuu2)
                        .addGap(78, 78, 78))))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btTracuu2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem2)
                    .addComponent(btnCapnhat2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel17))
        );

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblMuontraSach2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblMuontraSach2);

        jButton15.setBackground(java.awt.SystemColor.activeCaption);
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/thoat.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1091, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CbbTenSach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbTenSach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbTenSach2ActionPerformed

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        // TODO add your handling code here:
        int row = tblMuontraSach2.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn Đơn mượn muốn xóa","Thông báo", JOptionPane.ERROR_MESSAGE );
        }else
        {
            int confident = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa Đơn mượn này hay không!");
            if (confident == JOptionPane.YES_OPTION) {
                int dem=0;
                String maMuon = String.valueOf(tblMuontraSach2.getValueAt(row, 1));
                List<ThongTinMuonTra> user_ttmt = userTTMT.getAll();
                for(ThongTinMuonTra users : user_ttmt){
                    if(users.getNgayTra()!=""){
                        dem++;
                    }
                }
                if (dem==0){
                    JOptionPane.showMessageDialog(this,"Không thể xóa Đơn mượn vì đang mượn sách","Thông báo", JOptionPane.ERROR_MESSAGE );
                }
                else
                {
                    userTTMT.remove(maMuon);
                    defaultTableModel2.removeRow(row);

                }

            }

        }

    }//GEN-LAST:event_btnXoa2ActionPerformed

    private void btnCapnhat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhat2ActionPerformed
        // TODO add your handling code here:
        txtMaMuon2.setText("");
        txtMaDG2.setText("");
        CbbTenSach2.setSelectedItem(0);
        List<TuaSach> user_TS = userTS.getAll();
        for(TuaSach users : user_TS){
            CbbTenSach2.addItem(users.getTenTS());
        }
        txtGhichu2.setText("");
        txtSoluong2.setText("");
        //        try {
            //            txtNgayMuon2.setDate(f.parse(""));
            //            txtNgayHenTra2.setDate(f.parse(""));
            //            txtNgayTra2.setDate(f.parse(""));
            //        } catch (ParseException ex) {
            //            Logger.getLogger(Giaodien.class.getName()).log(Level.SEVERE, null, ex);
            //        }
        defaultTableModel2.setRowCount(0);
        List<ThongTinMuonTra> user_TTMT = userTTMT.getAll();
        int sttttmt=0;
        for(ThongTinMuonTra users : user_TTMT){
            sttttmt++;
            defaultTableModel2.addRow(new Object[]{sttttmt,users.getMaMuon(),users.getMaDG(),users.getMaDS(),users.getSoLuong(),users.getMaMuon(),users.getNgayHenTra(),users.getNgayTra()});
        }
    }//GEN-LAST:event_btnCapnhat2ActionPerformed

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        // TODO add your handling code here:
        String ngayMuon = f.format(txtNgayMuon2.getDate());
        String ngayHenTra = f.format(txtNgayHenTra2.getDate());
        String ngayTra = f.format(txtNgayTra2.getDate());
        ThongTinMuonTra thongTinMuonTra = new ThongTinMuonTra();
        thongTinMuonTra.setMaDG(txtMaDG2.getText());
        String tensach = String.valueOf(CbbTenSach2.getSelectedItem());
        List<TuaSach> user_TS = userTS.getAll();
        for(TuaSach user : user_TS){
            if(user.getTenTS().equals(tensach)){
                List<DauSach> user_DS = userDS.getAll();
                for(DauSach users : user_DS){
                    if (user.getMaTS().equals(users.getMaTS()))
                    thongTinMuonTra.setMaDS(users.getMaDS());
                }
            }
        }
        thongTinMuonTra.setSoLuong(Integer.valueOf(txtSoluong2.getText()));
        thongTinMuonTra.setNgayMuon(ngayMuon);
        thongTinMuonTra.setNgayHenTra(ngayHenTra);
        thongTinMuonTra.setNgayTra(ngayTra);
        List<ThongTinMuonTra> list = new ArrayList<ThongTinMuonTra>();
        list.add(thongTinMuonTra);
        userTTMT.insert(thongTinMuonTra);
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void btnLuu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu2ActionPerformed
        // TODO add your handling code here:
        String ngayMuon = f.format(txtNgayMuon2.getDate());
        String ngayHenTra = f.format(txtNgayHenTra2.getDate());
        String ngayTra = f.format(txtNgayTra2.getDate());
        ThongTinMuonTra thongTinMuonTra = new ThongTinMuonTra();
        thongTinMuonTra.setMaDG(txtMaDG2.getText());
        String tensach = String.valueOf(CbbTenSach2.getSelectedItem());
        List<TuaSach> user_TS = userTS.getAll();
        for(TuaSach user : user_TS){
            if(user.getTenTS().equals(tensach)){
                List<DauSach> user_DS = userDS.getAll();
                for(DauSach users : user_DS){
                    if (user.getMaTS().equals(users.getMaTS()))
                    thongTinMuonTra.setMaDS(users.getMaDS());
                }
            }
        }
        thongTinMuonTra.setMaMuon(txtMaMuon2.getText());
        thongTinMuonTra.setSoLuong(Integer.valueOf(txtSoluong2.getText()));
        thongTinMuonTra.setNgayMuon(ngayMuon);
        thongTinMuonTra.setNgayHenTra(ngayHenTra);
        thongTinMuonTra.setNgayTra(ngayTra);
        List<ThongTinMuonTra> list = new ArrayList<ThongTinMuonTra>();
        list.add(thongTinMuonTra);
        userTTMT.update(thongTinMuonTra);
    }//GEN-LAST:event_btnLuu2ActionPerformed

    private void btTracuu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTracuu2ActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(this,"Vui lòng nhập tên Độc giả",JOptionPane.INFORMATION_MESSAGE);

        List<DocGia> user_DG = userDG.findByName(str);
        for(DocGia user : user_DG){

            List<ThongTinMuonTra> user_TTMT = userTTMT.findByName(user.getMaDG());
            int sttttmt=0;
            defaultTableModel2.setRowCount(0);
            for(ThongTinMuonTra users : user_TTMT){
                sttttmt++;
                defaultTableModel2.addRow(new Object[]{sttttmt, users.getMaMuon(), users.getMaDG(), users.getMaDS(), users.getSoLuong(), users.getNgayMuon(), users.getNgayHenTra(), users.getNgayTra(), users.getGhiChu()});
            }
            if (defaultTableModel2.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Không tìm thấy","Thông báo", JOptionPane.ERROR_MESSAGE );
                List<ThongTinMuonTra> user_TTMT2 = userTTMT.getAll();
                int sttttmt2=0;
                for(ThongTinMuonTra users : user_TTMT2){
                    sttttmt2++;
                    defaultTableModel2.addRow(new Object[]{sttttmt2, users.getMaMuon(), users.getMaDG(), users.getMaDS(), users.getSoLuong(), users.getNgayMuon(), users.getNgayHenTra(), users.getNgayTra(), users.getGhiChu()});
                }
            }
        }

    }//GEN-LAST:event_btTracuu2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbTenSach2;
    private javax.swing.JButton btTracuu2;
    private javax.swing.JButton btnCapnhat2;
    private javax.swing.JButton btnLuu2;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblMuontraSach2;
    private javax.swing.JTextField txtGhichu2;
    private javax.swing.JTextField txtMaDG2;
    private javax.swing.JLabel txtMaMuon2;
    private com.toedter.calendar.JDateChooser txtNgayHenTra2;
    private com.toedter.calendar.JDateChooser txtNgayMuon2;
    private com.toedter.calendar.JDateChooser txtNgayTra2;
    private javax.swing.JTextField txtSoluong2;
    // End of variables declaration//GEN-END:variables
}
