/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import static java.lang.String.format;
import static java.lang.String.format;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import dao.DocGiaDao;
import dao.DauSachDao;
import dao.ThongTinMuonTraDao;
import dao.NhaXuatBanDao;
import dao.TacGiaDao;
import dao.TheLoaiDao;
import dao.TuaSachDao;
import model.DocGia;
import model.TacGia;
import model.TheLoai;
import model.TuaSach;
import model.DauSach;
import model.NhaXuatBan;
import model.ThongTinMuonTra;
import static view.ThongTinMuonSachPanel.maxPageItem;

/**
 *
 * @author Admin
 */
public class DauSachPanel extends javax.swing.JPanel {

    DefaultTableModel modelDauSach;
    DocGiaDao userDG;
    DauSachDao dauSachDao;
    ThongTinMuonTraDao userTTMT;
    NhaXuatBanDao userNXB;
    TacGiaDao userTG;
    TheLoaiDao userTL;
    TuaSachDao userTS;
    SimpleDateFormat f = new SimpleDateFormat("MMMM dd, yyyy");
    static int maxPageItem = 6;

    /**
     * Creates new form DM_sachJPanel
     */
    public DauSachPanel() {
        initComponents();

        modelDauSach = new DefaultTableModel() {
            @Override
            public java.lang.Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 5) {
                    return Boolean.class;
                } else {
                    return String.class;
                }
            }
        };

        dauSachDao = new DauSachDao();
        userNXB = new NhaXuatBanDao();
        userTS = new TuaSachDao();
        userTG = new TacGiaDao();
        userTL = new TheLoaiDao();
        tblDauSach.setModel(modelDauSach);

        modelDauSach.addColumn("STT");
        modelDauSach.addColumn("Mã đầu sách");
        modelDauSach.addColumn("Mã tựa sách");
        modelDauSach.addColumn("Ngôn ngữ");
        modelDauSach.addColumn("Mã nhà xuất bản");
        modelDauSach.addColumn("Đánh dấu");

        tblDauSach.setRowHeight(40);

        for (int i = 1; i <= dauSachDao.getTotalPage(maxPageItem); i++) {
            cbbDauSach.addItem(String.valueOf(i));
        }

        ShowDauSach(dauSachDao.getByPage(maxPageItem, 1), 0);
    }

    public void ShowDauSach() {
        List<DauSach> dausach = dauSachDao.getAll();
        int stt = 0;
        modelDauSach.setRowCount(0);
        for (DauSach show : dausach) {
            stt++;
            modelDauSach.addRow(new Object[]{stt, show.getMaDS(), show.getMaTS(), show.getNgonNgu(), show.getMaNXB(), false});

        }
    }

    public void ShowDauSach(List<DauSach> dausach, int viTri) {
        int stt = 0;
        stt += viTri;
        modelDauSach.setRowCount(0);
        for (DauSach show : dausach) {
            stt++;
            modelDauSach.addRow(new Object[]{stt, show.getMaDS(), show.getMaTS(), show.getNgonNgu(), show.getMaNXB(), false});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDauSach = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTenSach3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txttheloai3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTacGia3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNDtomluoc3 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        btnXoa3 = new javax.swing.JButton();
        btnCapnhat3 = new javax.swing.JButton();
        btnThem3 = new javax.swing.JButton();
        btnLuu3 = new javax.swing.JButton();
        btTracuu3 = new javax.swing.JButton();
        txtMaDauSach3 = new javax.swing.JLabel();
        RdbtnDamuon4 = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        txtNgonNgu3 = new javax.swing.JTextField();
        RdbtnChuamuon4 = new javax.swing.JRadioButton();
        jLabel42 = new javax.swing.JLabel();
        txtTenNXB3 = new javax.swing.JTextField();
        btnTiepTheo3 = new javax.swing.JButton();
        cbbDauSach = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnTruoc = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDauSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "TenSach", "MaDauSach", "LoaiSach", "Soluong"
            }
        ));
        tblDauSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDauSachMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDauSach);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1102, 270));

        jButton16.setBackground(java.awt.SystemColor.activeCaption);
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/thoat.png"))); // NOI18N
        jPanel3.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 864, 110, 51));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin danh mục sách"));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tên sách:");

        txtTenSach3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSach3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Mã đầu sách:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Tên thể loại");

        txttheloai3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttheloai3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Tác giả:");

        txtNDtomluoc3.setColumns(20);
        txtNDtomluoc3.setRows(5);
        jScrollPane2.setViewportView(txtNDtomluoc3);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Nội dung tóm lược:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Tình trạng:");

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnXoa3.setBackground(new java.awt.Color(0, 102, 153));
        btnXoa3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa3.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/delete (2).png"))); // NOI18N
        btnXoa3.setText("Xóa");
        btnXoa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa3ActionPerformed(evt);
            }
        });
        jPanel27.add(btnXoa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 140, 40));

        btnCapnhat3.setBackground(new java.awt.Color(0, 102, 153));
        btnCapnhat3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapnhat3.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/refresh (2).png"))); // NOI18N
        btnCapnhat3.setText("Làm mới");
        btnCapnhat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhat3ActionPerformed(evt);
            }
        });
        jPanel27.add(btnCapnhat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 140, 41));

        btnThem3.setBackground(new java.awt.Color(0, 102, 153));
        btnThem3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem3.setForeground(new java.awt.Color(255, 255, 255));
        btnThem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/add-button (1).png"))); // NOI18N
        btnThem3.setText("Thêm mới");
        btnThem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem3ActionPerformed(evt);
            }
        });
        jPanel27.add(btnThem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));

        btnLuu3.setBackground(new java.awt.Color(0, 102, 153));
        btnLuu3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu3.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/floppy-disk (1).png"))); // NOI18N
        btnLuu3.setText("Cập nhật");
        btnLuu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu3ActionPerformed(evt);
            }
        });
        jPanel27.add(btnLuu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 140, 44));

        btTracuu3.setBackground(new java.awt.Color(0, 102, 153));
        btTracuu3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTracuu3.setForeground(new java.awt.Color(255, 255, 255));
        btTracuu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/seo (2).png"))); // NOI18N
        btTracuu3.setText("Tra cứu");
        btTracuu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTracuu3ActionPerformed(evt);
            }
        });
        jPanel27.add(btTracuu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 150, 41));

        RdbtnDamuon4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        RdbtnDamuon4.setText("Đã mượn");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel37.setText("Ngôn ngữ:");

        RdbtnChuamuon4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        RdbtnChuamuon4.setText("Chưa mượn");
        RdbtnChuamuon4.setFocusable(false);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("Tên NXB:");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSach3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttheloai3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTacGia3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaDauSach3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel42))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addComponent(RdbtnDamuon4)
                                .addGap(23, 23, 23)
                                .addComponent(RdbtnChuamuon4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel37)
                                .addGap(18, 18, 18)
                                .addComponent(txtNgonNgu3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTenNXB3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addComponent(txtMaDauSach3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenSach3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttheloai3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTacGia3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(txtNgonNgu3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenNXB3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RdbtnDamuon4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RdbtnChuamuon4)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel25)))
                        .addGap(50, 50, 50))))
        );

        jPanel3.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1100, 420));

        btnTiepTheo3.setText("Tiếp theo");
        btnTiepTheo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepTheo3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnTiepTheo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, -1, 30));

        cbbDauSach.setEditable(true);
        cbbDauSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbDauSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDauSachActionPerformed(evt);
            }
        });
        jPanel3.add(cbbDauSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 710, 60, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trang");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 710, 50, 30));

        btnTruoc.setText("Trước");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });
        jPanel3.add(btnTruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 710, -1, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 795));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenSach3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSach3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSach3ActionPerformed

    private void txttheloai3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttheloai3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttheloai3ActionPerformed

    private void btnXoa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa3ActionPerformed
        // TODO add your handling code here:
        Boolean kiemTra = false;
        int row = tblDauSach.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Danh mục muốn xóa", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            int confident = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa Danh mục này hay không!");
            if (confident == JOptionPane.YES_OPTION) {

                for (int i = 0; i < tblDauSach.getRowCount(); i++) {
                    Boolean bool = Boolean.valueOf(tblDauSach.getValueAt(i, 5).toString());
                    if (bool == true) {
                        kiemTra = true;
                        String maDS = String.valueOf(tblDauSach.getValueAt(i, 1));
                        dauSachDao.remove(maDS);
                    }
                }

                if (!kiemTra) {
                    String maDS = String.valueOf(tblDauSach.getValueAt(row, 1));
                    dauSachDao.remove(maDS);
                }

                txtMaDauSach3.setText("");
                txtTenSach3.setText("");
                txttheloai3.setText("");
                txtTacGia3.setText("");
                RdbtnChuamuon4.setSelected(false);
                RdbtnDamuon4.setSelected(false);
                txtNDtomluoc3.setText("");
                txtNgonNgu3.setText("");
                txtTenNXB3.setText("");

                int selectedPage = Integer.parseInt(cbbDauSach.getSelectedItem().toString());
                ShowDauSach(dauSachDao.getByPage(maxPageItem, selectedPage), (selectedPage - 1) * maxPageItem);

                JOptionPane.showConfirmDialog(this, "Xóa danh mục thành công");
            }

        }
    }//GEN-LAST:event_btnXoa3ActionPerformed

    private void btnCapnhat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhat3ActionPerformed
        // TODO add your handling code here:
        txtMaDauSach3.setText("");
        txtTenSach3.setText("");
        txttheloai3.setText("");
        txtTacGia3.setText("");
        RdbtnChuamuon4.setSelected(false);
        RdbtnDamuon4.setSelected(false);
        txtNDtomluoc3.setText("");
        txtNgonNgu3.setText("");
        txtTenNXB3.setText("");
        ShowDauSach(dauSachDao.getByPage(maxPageItem, 1), 0);
    }//GEN-LAST:event_btnCapnhat3ActionPerformed

    private void btnThem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem3ActionPerformed
        // TODO add your handling code here:

        DauSach dauSach = new DauSach();
        List<TuaSach> user_TS = userTS.getAll();
        if (txtTenSach3.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập đầy đủ thông tin");
        }
        else{
        int dem1 = 0;
        int dem2 = 0;
        for (TuaSach users : user_TS) {
            dem1++;
            if (users.getTenTS().equals(txtTenSach3.getText())) {
                dauSach.setMaTS(users.getMaTS());
                break;
            } else {
                dem2++;
            }
        }
        if (dem1 == dem2) {
            JOptionPane.showMessageDialog(this, "Không có tên sách bạn đã nhập!\n Vui lòng kiểm tra lại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            dauSach.setNgonNgu(txtNgonNgu3.getText());
            List<NhaXuatBan> user_NXB = userNXB.getAll();
            int dem3 = 0;
            int dem4 = 0;
            for (NhaXuatBan users : user_NXB) {
                dem3++;
                if (users.getTenNXB().equals(txtTenNXB3.getText())) {
                    dauSach.setMaNXB(users.getMaNXB());
                } else {
                    dem4++;
                }
            }
            if (dem3 == dem4) {
                JOptionPane.showMessageDialog(this, "Không có tên Nhà xuất bản bạn đã nhập!\n Vui lòng kiểm tra lại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {

                

                    int totalPage = dauSachDao.getTotalPage(maxPageItem);
                    if (totalPage == cbbDauSach.getItemCount() + 1) {
                        cbbDauSach.addItem(String.valueOf(totalPage));
                    }
                    cbbDauSach.setSelectedIndex(totalPage - 1);

                    txtMaDauSach3.setText("");
                    txtTenSach3.setText("");
                    txttheloai3.setText("");
                    txtTacGia3.setText("");
                    RdbtnChuamuon4.setSelected(false);
                    RdbtnDamuon4.setSelected(false);
                    txtNDtomluoc3.setText("");
                    txtNgonNgu3.setText("");
                    txtTenNXB3.setText("");

                    JOptionPane.showConfirmDialog(this, "Thêm đầu sách thành công");
                }

            }
        }
    }//GEN-LAST:event_btnThem3ActionPerformed

    private void btnLuu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu3ActionPerformed
        // TODO add your handling code here:
        DauSach dauSach = new DauSach();
        dauSach.setMaDS(txtMaDauSach3.getText());
        dauSach.setMaTS(txtMaDauSach3.getText());
        List<TuaSach> user_TS = userTS.getAll();
        int dem1 = 0;
        int dem2 = 0;
        for (TuaSach users : user_TS) {
            dem1++;
            if (users.getTenTS().equals(txtTenSach3.getText())) {
                dauSach.setMaTS(users.getMaTS());
                break;
            } else {
                dem2++;
            }
        }
        if (dem1 == dem2) {
            JOptionPane.showMessageDialog(this, "Không có tên sách bạn đã nhập!\n Vui lòng kiểm tra lại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            dauSach.setNgonNgu(txtNgonNgu3.getText());
            List<NhaXuatBan> user_NXB = userNXB.getAll();
            int dem3 = 0;
            int dem4 = 0;
            for (NhaXuatBan users : user_NXB) {
                dem3++;
                if (users.getTenNXB().equals(txtTenNXB3.getText())) {
                    dauSach.setMaNXB(users.getMaNXB());
                } else {
                    dem4++;
                }
            }
            if (dem3 == dem4) {
                JOptionPane.showMessageDialog(this, "Không có tên Nhà xuất bản bạn đã nhập!\n Vui lòng kiểm tra lại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {

                dauSachDao.update(dauSach);
                JOptionPane.showConfirmDialog(this, "Cập nhật danh mục thành công");
                txtMaDauSach3.setText("");
                txtTenSach3.setText("");
                txttheloai3.setText("");
                txtTacGia3.setText("");
                RdbtnChuamuon4.setSelected(false);
                RdbtnDamuon4.setSelected(false);
                txtNDtomluoc3.setText("");
                txtNgonNgu3.setText("");
                txtTenNXB3.setText("");
                ShowDauSach();
            }
        }
    }//GEN-LAST:event_btnLuu3ActionPerformed

    private void btTracuu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTracuu3ActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(this, "Vui lòng nhập tên Tựa sách", JOptionPane.INFORMATION_MESSAGE);
        if (str != null) {
            modelDauSach.setRowCount(0);
            List<TuaSach> tuasach = userTS.findByName(str);
            for (TuaSach user : tuasach) {
                List<DauSach> dausach = dauSachDao.findByName(user.getMaTS());
                int stt = 0;

                for (DauSach show : dausach) {

                    stt++;
                    modelDauSach.addRow(new Object[]{stt, show.getMaDS(), show.getMaTS(), show.getNgonNgu(), show.getMaNXB()});

                }

            }
            if (modelDauSach.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy", "Thông báo", JOptionPane.ERROR_MESSAGE);
                ShowDauSach();
            }
        }
    }//GEN-LAST:event_btTracuu3ActionPerformed

    private void tblDauSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDauSachMouseClicked
        // TODO add your handling code here:
        int row = tblDauSach.getSelectedRow();
        txtMaDauSach3.setText(String.valueOf(tblDauSach.getValueAt(row, 1)));
        String string = String.valueOf(tblDauSach.getValueAt(row, 1));

        List<DauSach> user_DS2 = dauSachDao.getAll();
        for (DauSach users_DS : user_DS2) {
            if (string.equals(users_DS.getMaDS())) {
                List<TuaSach> user_TS2 = userTS.getAll();
                for (TuaSach users_TS : user_TS2) {
                    if (users_DS.getMaTS().equals(users_TS.getMaTS())) {
                        txtTenSach3.setText(users_TS.getTenTS());
                        List<TheLoai> user_TL2 = userTL.getAll();
                        for (TheLoai userss : user_TL2) {
                            if (users_TS.getMaTL().equals(userss.getMaTL())) {
                                txttheloai3.setText(userss.getTenTL());
                            }
                        }
                        List<TacGia> user_TG2 = userTG.getAll();
                        for (TacGia users_TG : user_TG2) {
                            if (users_TS.getMaTG().equals(users_TG.getMaTG())) {
                                txtTacGia3.setText(users_TG.getHoten());
                            }
                        }
                        if (users_TS.getSoLuong() > 0) {
                            RdbtnChuamuon4.setSelected(true);
                        } else {
                            RdbtnDamuon4.setSelected(true);
                        }
                        txtNDtomluoc3.setText(users_TS.getTomTat());
                    }

                }
            }

        }
        txtNgonNgu3.setText(String.valueOf(tblDauSach.getValueAt(row, 3)));
        List<NhaXuatBan> user_NXB = userNXB.getAll();
        for (NhaXuatBan users : user_NXB) {
            if (users.getMaNXB().equals(String.valueOf(tblDauSach.getValueAt(row, 4)))) {
                txtTenNXB3.setText(users.getTenNXB());
            }
        }
    }//GEN-LAST:event_tblDauSachMouseClicked

    private void btnTiepTheo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepTheo3ActionPerformed
        int totalPage = dauSachDao.getTotalPage(maxPageItem);
        cbbDauSach.setSelectedIndex(cbbDauSach.getSelectedIndex() == totalPage - 1 ? totalPage - 1 : cbbDauSach.getSelectedIndex() + 1);
    }//GEN-LAST:event_btnTiepTheo3ActionPerformed

    private void cbbDauSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDauSachActionPerformed
        int selectedPage = Integer.parseInt(cbbDauSach.getSelectedItem().toString());
        ShowDauSach(dauSachDao.getByPage(maxPageItem, selectedPage), (selectedPage - 1) * maxPageItem);
    }//GEN-LAST:event_cbbDauSachActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        cbbDauSach.setSelectedIndex(cbbDauSach.getSelectedIndex() == 0 ? 0 : cbbDauSach.getSelectedIndex() - 1);
    }//GEN-LAST:event_btnTruocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdbtnChuamuon4;
    private javax.swing.JRadioButton RdbtnDamuon4;
    private javax.swing.JButton btTracuu3;
    private javax.swing.JButton btnCapnhat3;
    private javax.swing.JButton btnLuu3;
    private javax.swing.JButton btnThem3;
    private javax.swing.JButton btnTiepTheo3;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnXoa3;
    private javax.swing.JComboBox<String> cbbDauSach;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblDauSach;
    private javax.swing.JLabel txtMaDauSach3;
    private javax.swing.JTextArea txtNDtomluoc3;
    private javax.swing.JTextField txtNgonNgu3;
    private javax.swing.JTextField txtTacGia3;
    private javax.swing.JTextField txtTenNXB3;
    private javax.swing.JTextField txtTenSach3;
    private javax.swing.JTextField txttheloai3;
    // End of variables declaration//GEN-END:variables
}
