/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import static java.lang.String.format;
import static java.lang.String.format;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import dao.DocGiaDao;
import dao.DauSachDao;
import dao.ThongTinMuonTraDao;
import dao.NhaXuatBanDao;
import dao.TacGiaDao;
import dao.TheLoaiDao;
import dao.TuaSachDao;
import model.DocGia;
import model.TacGia;
import model.TheLoai;
import model.TuaSach;
import model.DauSach;
import model.NhaXuatBan;
import model.ThongTinMuonTra;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import dao.DauSachDao;
import dao.DocGiaDao;
import dao.NhaXuatBanDao;
import dao.TacGiaDao;
import dao.TheLoaiDao;
import dao.ThongTinMuonTraDao;
import dao.TuaSachDao;

/**
 *
 * @author Admin
 */
public class ThongTinMuonSachPanel extends javax.swing.JPanel {

    DefaultTableModel modelMuonSach;
    DocGiaDao userDG;
    DauSachDao userDS;
    ThongTinMuonTraDao thongTinMuonTraDao;
    NhaXuatBanDao userNXB;
    TacGiaDao userTG;
    TheLoaiDao userTL;
    TuaSachDao userTS;
    static int maxPageItem = 8;
    SimpleDateFormat f = new SimpleDateFormat("MMMM dd, yyyy");

    /**
     * Creates new form Muon_traSachJPanel
     */
    public ThongTinMuonSachPanel() {
        initComponents();
        modelMuonSach = new DefaultTableModel() {
            @Override
            public java.lang.Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 9) {
                    return Boolean.class;
                } else {
                    return String.class;
                }
            }
        };

        thongTinMuonTraDao = new ThongTinMuonTraDao();
        userTS = new TuaSachDao();
        userDS = new DauSachDao();
        userDG = new DocGiaDao();

        tblMuontraSach2.setModel(modelMuonSach);

        modelMuonSach.addColumn("STT");
        modelMuonSach.addColumn("Mã mượn");
        modelMuonSach.addColumn("Mã độc giả");
        modelMuonSach.addColumn("Mã đầu sách");
        modelMuonSach.addColumn("Số lượng");
        modelMuonSach.addColumn("Ngày mượn");
        modelMuonSach.addColumn("Ngày hẹn trả");
        modelMuonSach.addColumn("Ngày trả");
        modelMuonSach.addColumn("Ghi chú");
        modelMuonSach.addColumn("Đánh dấu");

        tblMuontraSach2.setRowHeight(40);
        tblMuontraSach2.getColumnModel().getColumn(0).setPreferredWidth(20);
        tblMuontraSach2.getColumnModel().getColumn(9).setPreferredWidth(20);

        List<TuaSach> user_TS = userTS.getAll();
        for (TuaSach users : user_TS) {
            CbbTenSach2.addItem(users.getTenTS());
        }

        for (int i = 1; i <= thongTinMuonTraDao.getTotalPage(maxPageItem); i++) {
            cbbMuon.addItem(String.valueOf(i));
        }

        ShowMuonTra(thongTinMuonTraDao.getByPage(maxPageItem, 1), 0);
    }

    public void ShowMuonTra() {
        List<ThongTinMuonTra> thongTinMuonTra = thongTinMuonTraDao.getAll();
        int stt = 0;
        modelMuonSach.setRowCount(0);
        for (ThongTinMuonTra show : thongTinMuonTra) {
            stt++;
            modelMuonSach.addRow(new Object[]{stt, show.getMaMuon(), show.getMaDG(), show.getMaDS(), show.getSoLuong(),
                show.getNgayMuon(), show.getNgayHenTra(), show.getNgayTra(), show.getGhiChu(), false});
        }
    }

    public void ShowMuonTra(List<ThongTinMuonTra> thongTinMuonTra, int viTri) {
        int stt = 0;
        stt = stt + viTri;
        modelMuonSach.setRowCount(0);
        for (ThongTinMuonTra show : thongTinMuonTra) {
            stt++;
            modelMuonSach.addRow(new Object[]{stt, show.getMaMuon(), show.getMaDG(), show.getMaDS(), show.getSoLuong(),
                show.getNgayMuon(), show.getNgayHenTra(), show.getNgayTra(), show.getGhiChu(), false});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        CbbTenSach2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtSoluong2 = new javax.swing.JTextField();
        txtGhichu2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNgayMuon2 = new com.toedter.calendar.JDateChooser();
        txtNgayHenTra2 = new com.toedter.calendar.JDateChooser();
        txtNgayTra2 = new com.toedter.calendar.JDateChooser();
        txtMaMuon2 = new javax.swing.JLabel();
        txtMaDG2 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        btnXoa2 = new javax.swing.JButton();
        btnCapnhat2 = new javax.swing.JButton();
        btnThem2 = new javax.swing.JButton();
        btnLuu2 = new javax.swing.JButton();
        btTracuu2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMuontraSach2 = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbbMuon = new javax.swing.JComboBox<>();
        btnTiepTheo = new javax.swing.JButton();
        btnTruoc = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(0, 102, 153));

        jPanel20.setBackground(new java.awt.Color(0, 102, 153));
        jPanel20.setForeground(new java.awt.Color(0, 102, 153));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin mượn trả"));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Mã mượn:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Mã đọc giả");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Tên sách:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Ngày mượn:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Ngày hẹn trả:");

        CbbTenSach2.setBackground(new java.awt.Color(204, 255, 255));
        CbbTenSach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbTenSach2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Số lượng:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Ghi chú:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ngày trả:");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23)
                    .addComponent(jLabel20))
                .addGap(32, 32, 32)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(txtSoluong2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaMuon2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaDG2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CbbTenSach2, 0, 332, Short.MAX_VALUE)
                                    .addComponent(txtGhichu2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(40, 40, 40)
                                .addComponent(txtNgayTra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel21Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNgayHenTra2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel21Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNgayMuon2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaMuon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtMaDG2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbbTenSach2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayMuon2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayHenTra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGhichu2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNgayTra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtSoluong2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnXoa2.setBackground(new java.awt.Color(0, 102, 153));
        btnXoa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa2.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/delete (2).png"))); // NOI18N
        btnXoa2.setText("Xóa");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });
        jPanel24.add(btnXoa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 200, 130, 43));

        btnCapnhat2.setBackground(new java.awt.Color(0, 102, 153));
        btnCapnhat2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapnhat2.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/refresh (2).png"))); // NOI18N
        btnCapnhat2.setText("Làm mới");
        btnCapnhat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhat2ActionPerformed(evt);
            }
        });
        jPanel24.add(btnCapnhat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 41));

        btnThem2.setBackground(new java.awt.Color(0, 102, 153));
        btnThem2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem2.setForeground(new java.awt.Color(255, 255, 255));
        btnThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/add-button (1).png"))); // NOI18N
        btnThem2.setText("Thêm mới");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });
        jPanel24.add(btnThem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        btnLuu2.setBackground(new java.awt.Color(0, 102, 153));
        btnLuu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu2.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/floppy-disk (1).png"))); // NOI18N
        btnLuu2.setText("Cập nhật");
        btnLuu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu2ActionPerformed(evt);
            }
        });
        jPanel24.add(btnLuu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 130, 40));

        btTracuu2.setBackground(new java.awt.Color(0, 102, 153));
        btTracuu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTracuu2.setForeground(new java.awt.Color(255, 255, 255));
        btTracuu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/seo (2).png"))); // NOI18N
        btTracuu2.setText("Tra cứu");
        btTracuu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTracuu2ActionPerformed(evt);
            }
        });
        jPanel24.add(btTracuu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, 42));

        tblMuontraSach2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMuontraSach2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMuontraSach2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMuontraSach2);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jButton15.setBackground(java.awt.SystemColor.activeCaption);
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/thoat.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(566, 566, 566)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trang");

        cbbMuon.setEditable(true);
        cbbMuon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMuonActionPerformed(evt);
            }
        });

        btnTiepTheo.setText("Tiếp theo");
        btnTiepTheo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepTheoActionPerformed(evt);
            }
        });

        btnTruoc.setText("Trước");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(btnTruoc)
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cbbMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnTiepTheo)
                .addContainerGap(417, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 26, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(715, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTiepTheo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 53, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CbbTenSach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbTenSach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbTenSach2ActionPerformed

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        // TODO add your handling code here:
        Boolean kiemTra = false;

        int row = tblMuontraSach2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Đơn mượn muốn xóa", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {

            int confident = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa Đơn mượn này hay không!");
            if (confident == JOptionPane.YES_OPTION) {
                for (int i = 0; i < tblMuontraSach2.getRowCount(); i++) {
                    Boolean bool = Boolean.valueOf(tblMuontraSach2.getValueAt(i, 9).toString());
                    if (bool == true) {
                        kiemTra = true;
                        String maMuon = String.valueOf(tblMuontraSach2.getValueAt(i, 1));
                        thongTinMuonTraDao.remove(maMuon);
                    }
                }

                if (!kiemTra) {
                    String maMuon = String.valueOf(tblMuontraSach2.getValueAt(row, 1));
                    thongTinMuonTraDao.remove(maMuon);
                }

                txtMaMuon2.setText("");
                txtMaDG2.setText("");
                CbbTenSach2.setSelectedIndex(0);
                List<TuaSach> user_TS = userTS.getAll();
                for (TuaSach users : user_TS) {
                    CbbTenSach2.addItem(users.getTenTS());
                }
                txtGhichu2.setText("");
                txtSoluong2.setText("");
                int selectedPage = Integer.parseInt(cbbMuon.getSelectedItem().toString());
                ShowMuonTra(thongTinMuonTraDao.getByPage(maxPageItem, selectedPage), (selectedPage - 1) * maxPageItem);
                JOptionPane.showConfirmDialog(this, "Xóa phiếu mượn thành công");

            }

        }

    }//GEN-LAST:event_btnXoa2ActionPerformed

    private void btnCapnhat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhat2ActionPerformed
        // TODO add your handling code here:
        txtMaMuon2.setText("");
        txtMaDG2.setText("");
        CbbTenSach2.setSelectedIndex(0);
        List<TuaSach> user_TS = userTS.getAll();
        for (TuaSach users : user_TS) {
            CbbTenSach2.addItem(users.getTenTS());
        }
        txtGhichu2.setText("");
        txtSoluong2.setText("");
        ShowMuonTra(thongTinMuonTraDao.getByPage(maxPageItem, 1), 0);
    }//GEN-LAST:event_btnCapnhat2ActionPerformed

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        // TODO add your handling code here:

        if (txtMaDG2.getText().equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập đầy đủ thông tin");
        } else {
            String ngayMuon = f.format(txtNgayMuon2.getDate());
            String ngayHenTra = f.format(txtNgayHenTra2.getDate());
            ThongTinMuonTra thongTinMuonTra = new ThongTinMuonTra();
            thongTinMuonTra.setMaDG(txtMaDG2.getText());
            String tensach = String.valueOf(CbbTenSach2.getSelectedItem());
            List<TuaSach> user_TS = userTS.getAll();
            for (TuaSach user : user_TS) {
                if (user.getTenTS().equals(tensach)) {
                    List<DauSach> user_DS = userDS.getAll();
                    for (DauSach users : user_DS) {
                        if (user.getMaTS().equals(users.getMaTS())) {
                            thongTinMuonTra.setMaDS(users.getMaDS());
                        }
                    }
                }
            }
            thongTinMuonTra.setSoLuong(Integer.valueOf(txtSoluong2.getText()));
            thongTinMuonTra.setNgayMuon(ngayMuon);
            thongTinMuonTra.setNgayHenTra(ngayHenTra);
            thongTinMuonTra.setGhiChu(txtGhichu2.getText());
            thongTinMuonTraDao.insert(thongTinMuonTra);

            int totalPage = thongTinMuonTraDao.getTotalPage(maxPageItem);
            if (totalPage == cbbMuon.getItemCount() + 1) {
                cbbMuon.addItem(String.valueOf(totalPage));
            }
            cbbMuon.setSelectedIndex(totalPage - 1);

            txtMaMuon2.setText("");
            txtMaDG2.setText("");
            CbbTenSach2.setSelectedIndex(0);
            List<TuaSach> user_TS1 = userTS.getAll();
            for (TuaSach users : user_TS1) {
                CbbTenSach2.addItem(users.getTenTS());
            }
            txtGhichu2.setText("");
            txtSoluong2.setText("");

            JOptionPane.showConfirmDialog(this, "Thêm phiếu mượn thành công");
        }

    }//GEN-LAST:event_btnThem2ActionPerformed

    private void btnLuu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu2ActionPerformed
        // TODO add your handling code here:
        String ngayMuon = f.format(txtNgayMuon2.getDate());
        String ngayHenTra = f.format(txtNgayHenTra2.getDate());
        String ngayTra = f.format(txtNgayTra2.getDate());
        ThongTinMuonTra thongTinMuonTra = new ThongTinMuonTra();
        thongTinMuonTra.setMaDG(txtMaDG2.getText());
        String tensach = String.valueOf(CbbTenSach2.getSelectedItem());
        List<TuaSach> user_TS = userTS.getAll();
        for (TuaSach user : user_TS) {
            if (user.getTenTS().equals(tensach)) {
                List<DauSach> user_DS = userDS.getAll();
                for (DauSach users : user_DS) {
                    if (user.getMaTS().equals(users.getMaTS())) {
                        thongTinMuonTra.setMaDS(users.getMaDS());
                    }
                }
            }
        }
        thongTinMuonTra.setMaMuon(txtMaMuon2.getText());
        thongTinMuonTra.setSoLuong(Integer.valueOf(txtSoluong2.getText()));
        thongTinMuonTra.setNgayMuon(ngayMuon);
        thongTinMuonTra.setNgayHenTra(ngayHenTra);
        thongTinMuonTra.setNgayTra(ngayTra);
        thongTinMuonTra.setGhiChu(txtGhichu2.getText());
        if (!txtMaDG2.getText().equals("") && !txtSoluong2.getText().equals("")) {
            thongTinMuonTraDao.update(thongTinMuonTra);

            int totalPage = thongTinMuonTraDao.getTotalPage(maxPageItem);
            if (totalPage == cbbMuon.getItemCount() + 1) {
                cbbMuon.addItem(String.valueOf(totalPage));
            }
            cbbMuon.setSelectedIndex(totalPage - 1);

            txtMaMuon2.setText("");
            txtMaDG2.setText("");
            CbbTenSach2.setSelectedIndex(0);
            List<TuaSach> user_TS1 = userTS.getAll();
            for (TuaSach users : user_TS1) {
                CbbTenSach2.addItem(users.getTenTS());
            }
            txtGhichu2.setText("");
            txtSoluong2.setText("");

            JOptionPane.showConfirmDialog(this, "Thêm phiếu mượn thành công");
        } else
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập đầy đủ thông tin");
    }//GEN-LAST:event_btnLuu2ActionPerformed

    private void btTracuu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTracuu2ActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(this, "Vui lòng nhập tên Độc giả", JOptionPane.INFORMATION_MESSAGE);
        if (str != null) {
            List<DocGia> user_DG = userDG.findByName(str);
            for (DocGia user : user_DG) {

                List<ThongTinMuonTra> user_TTMT = thongTinMuonTraDao.findByName(user.getMaDG());
                int sttttmt = 0;
                modelMuonSach.setRowCount(0);
                for (ThongTinMuonTra users : user_TTMT) {
                    sttttmt++;
                    modelMuonSach.addRow(new Object[]{sttttmt, users.getMaMuon(), users.getMaDG(), users.getMaDS(), users.getSoLuong(), users.getNgayMuon(), users.getNgayHenTra(), users.getNgayTra(), users.getGhiChu()});
                }
                if (modelMuonSach.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    ShowMuonTra();
                }
            }
        }

    }//GEN-LAST:event_btTracuu2ActionPerformed

    private void tblMuontraSach2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMuontraSach2MouseClicked
        // TODO add your handling code here:
        int row = tblMuontraSach2.getSelectedRow();
        txtMaMuon2.setText(String.valueOf(tblMuontraSach2.getValueAt(row, 1)));
        txtMaDG2.setText(String.valueOf(tblMuontraSach2.getValueAt(row, 2)));
        String string = String.valueOf(tblMuontraSach2.getValueAt(row, 3));
        List<ThongTinMuonTra> user_TTMT2 = thongTinMuonTraDao.getAll();
        for (ThongTinMuonTra user : user_TTMT2) {
            List<DauSach> user_DS2 = userDS.getAll();
            for (DauSach users : user_DS2) {
                if (string.equals(users.getMaDS())) {
                    List<TuaSach> user_TS2 = userTS.getAll();
                    for (TuaSach userss : user_TS2) {
                        if (users.getMaTS().equals(userss.getMaTS())) {
                            CbbTenSach2.setSelectedItem(userss.getTenTS());
                        }
                    }
                }
            }
        }
        txtSoluong2.setText(String.valueOf(tblMuontraSach2.getValueAt(row, 4)));
        txtGhichu2.setText(String.valueOf(tblMuontraSach2.getValueAt(row, 8)));

        String str1 = String.valueOf(tblMuontraSach2.getValueAt(row, 5));
        String str2 = String.valueOf(tblMuontraSach2.getValueAt(row, 6));
        String str3 = "";
        if (String.valueOf(tblMuontraSach2.getValueAt(row, 7)) != null) {
            str3 += String.valueOf(tblMuontraSach2.getValueAt(row, 7));
        } else {
            str3 = "";
        }
        try {
            Date NgayMuon = f.parse(str1);
            Date NgayHenTra = f.parse(str2);
            Date NgayTra = f.parse(str3);
            txtNgayMuon2.setDate(NgayMuon);
            txtNgayHenTra2.setDate(NgayHenTra);
            txtNgayTra2.setDate(NgayTra);
        } catch (ParseException ex) {
            Logger.getLogger(ThongTinMuonSachPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblMuontraSach2MouseClicked

    private void btnTiepTheoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepTheoActionPerformed
        int totalPage = thongTinMuonTraDao.getTotalPage(maxPageItem);
        cbbMuon.setSelectedIndex(cbbMuon.getSelectedIndex() == totalPage - 1 ? totalPage - 1 : cbbMuon.getSelectedIndex() + 1);
    }//GEN-LAST:event_btnTiepTheoActionPerformed

    private void cbbMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMuonActionPerformed
        int selectedPage = Integer.parseInt(cbbMuon.getSelectedItem().toString());
        ShowMuonTra(thongTinMuonTraDao.getByPage(maxPageItem, selectedPage), (selectedPage - 1) * maxPageItem);
    }//GEN-LAST:event_cbbMuonActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        cbbMuon.setSelectedIndex(cbbMuon.getSelectedIndex() == 0 ? 0 : cbbMuon.getSelectedIndex() - 1);
    }//GEN-LAST:event_btnTruocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbTenSach2;
    private javax.swing.JButton btTracuu2;
    private javax.swing.JButton btnCapnhat2;
    private javax.swing.JButton btnLuu2;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnTiepTheo;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JComboBox<String> cbbMuon;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblMuontraSach2;
    private javax.swing.JTextField txtGhichu2;
    private javax.swing.JTextField txtMaDG2;
    private javax.swing.JLabel txtMaMuon2;
    private com.toedter.calendar.JDateChooser txtNgayHenTra2;
    private com.toedter.calendar.JDateChooser txtNgayMuon2;
    private com.toedter.calendar.JDateChooser txtNgayTra2;
    private javax.swing.JTextField txtSoluong2;
    // End of variables declaration//GEN-END:variables
}
