package main.view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
import java.awt.BorderLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import static java.lang.String.format;
import static java.lang.String.format;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import main.dao.DocGiaDao;
import main.dao.DauSachDao;
import main.dao.ThongTinMuonTraDao;
import main.dao.NhaXuatBanDao;
import main.dao.TacGiaDao;
import main.dao.TheLoaiDao;
import main.dao.TuaSachDao;
import main.model.DocGia;
import main.model.TacGia;
import main.model.TheLoai;
import main.model.TuaSach;
import main.model.DauSach;
import main.model.NhaXuatBan;
import main.model.ThongTinMuonTra;

public class DocGiaPanel extends javax.swing.JPanel {

    /**
     * Creates new form DocGiaPanel
     */
    DefaultTableModel modelDocGia;
    DocGiaDao userDG;
    DauSachDao userDS;
    ThongTinMuonTraDao userTTMT;
    NhaXuatBanDao userNXB;
    TacGiaDao userTG;
    TheLoaiDao userTL;
    TuaSachDao userTS;
    SimpleDateFormat f = new SimpleDateFormat("MMMM dd, yyyy");

    public DocGiaPanel() {
        initComponents();
        modelDocGia = new DefaultTableModel();
        tblDocGia1.setModel(modelDocGia);
        userDG = new DocGiaDao();
        userTTMT = new ThongTinMuonTraDao();
        modelDocGia.addColumn("STT");
        modelDocGia.addColumn("Mã độc giả");
        modelDocGia.addColumn("Họ tên");
        modelDocGia.addColumn("Giới tính");
        modelDocGia.addColumn("Ngày sinh");
        modelDocGia.addColumn("Địa chỉ");
        modelDocGia.addColumn("SĐT");
        modelDocGia.addColumn("Ngày đăng kí");
        modelDocGia.addColumn("Ngày hết hạn");
        tblDocGia1.setRowHeight(40);
        ShowDocGia();

    }

    public void ShowDocGia() {
        List<DocGia> docgia = userDG.getAll();
        modelDocGia.setRowCount(0);
        int stt = 0;
        for (DocGia show : docgia) {
            stt++;
            modelDocGia.addRow(new Object[]{stt, show.getMaDG(), show.getHoten(), show.getGioiTinh(), show.getNgaySinh(), show.getDiaChi(), show.getSdt(), show.getNgayDK(), show.getNgayHetHan()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoDT1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiaChi1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        RdbtnNam1 = new javax.swing.JRadioButton();
        RdbtnNu1 = new javax.swing.JRadioButton();
        txtMaDocGia1 = new javax.swing.JLabel();
        txtNgaySinh1 = new com.toedter.calendar.JDateChooser();
        txtngayDK1 = new com.toedter.calendar.JDateChooser();
        txtngayEndDK1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocGia1 = new javax.swing.JTable();
        jPanel28 = new javax.swing.JPanel();
        btnThem1 = new javax.swing.JButton();
        btnCapnhat1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnLuu1 = new javax.swing.JButton();
        btTracuu1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 102, 153));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết đọc giả"));

        jLabel2.setText("Mã đọc giả:");

        jLabel3.setText("Số điện thoại:");

        jLabel4.setText("Địa chỉ:");

        txtHoTen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTen1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Họ tên:");

        jLabel6.setText("Ngày sinh:");

        jLabel7.setText("Ngày đăng kí:");

        jLabel8.setText("Ngày hết hạn:");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Giới tính"));

        buttonGroup1.add(RdbtnNam1);
        RdbtnNam1.setText("Nam");

        buttonGroup1.add(RdbtnNu1);
        RdbtnNu1.setText("Nữ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RdbtnNam1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(RdbtnNu1)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdbtnNam1)
                    .addComponent(RdbtnNu1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNgaySinh1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtngayEndDK1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtngayDK1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDiaChi1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaDocGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(45, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtSoDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaDocGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txtDiaChi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgaySinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtngayDK1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(txtngayEndDK1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 740, 330));

        tblDocGia1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDocGia1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDocGia1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblDocGia1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblDocGia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDocGia1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDocGia1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 333, 1086, 352));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnThem1.setBackground(new java.awt.Color(0, 102, 153));
        btnThem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem1.setForeground(new java.awt.Color(255, 255, 255));
        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/add-button (1).png"))); // NOI18N
        btnThem1.setText("Add");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnCapnhat1.setBackground(new java.awt.Color(0, 102, 153));
        btnCapnhat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapnhat1.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/refresh (2).png"))); // NOI18N
        btnCapnhat1.setText("Refresh");
        btnCapnhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhat1ActionPerformed(evt);
            }
        });

        btnXoa1.setBackground(new java.awt.Color(0, 102, 153));
        btnXoa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa1.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/delete (2).png"))); // NOI18N
        btnXoa1.setText("Delete");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnLuu1.setBackground(new java.awt.Color(0, 102, 153));
        btnLuu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu1.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/floppy-disk (1).png"))); // NOI18N
        btnLuu1.setText("Save");
        btnLuu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu1ActionPerformed(evt);
            }
        });

        btTracuu1.setBackground(new java.awt.Color(0, 102, 153));
        btTracuu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTracuu1.setForeground(new java.awt.Color(255, 255, 255));
        btTracuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/seo (2).png"))); // NOI18N
        btTracuu1.setText("Tra cứu");
        btTracuu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTracuu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnXoa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCapnhat1)
                        .addGap(31, 31, 31)))
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLuu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48))
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btTracuu1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btTracuu1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapnhat1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem1))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 1, 340, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1091, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1091, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        String ngaySinh = f.format(txtNgaySinh1.getDate());
        String ngayDK = f.format(txtngayDK1.getDate());
        String ngayEndDK = f.format(txtngayEndDK1.getDate());

        String gioitinh = "";
        if (RdbtnNam1.isSelected()) {
            gioitinh += "Nam";
        } else {
            gioitinh += "Nữ";
        }
        DocGia docGia = new DocGia();
        docGia.setHoten(txtHoTen1.getText());
        docGia.setDiaChi(txtDiaChi1.getText());
        docGia.setGioiTinh(gioitinh);
        docGia.setSdt(txtSoDT1.getText());
        docGia.setNgaySinh(ngaySinh);
        docGia.setNgayDK(ngayDK);
        docGia.setNgayHetHan(ngayEndDK);
        userDG.insert(docGia);
        JOptionPane.showConfirmDialog(this, "Thêm thành công");
        ShowDocGia();

        txtHoTen1.setText("");
        txtMaDocGia1.setText("");
        txtDiaChi1.setText("");
        txtSoDT1.setText("");
        RdbtnNam1.setSelected(false);
        RdbtnNu1.setSelected(false);
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnCapnhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhat1ActionPerformed
        // TODO add your handling code here:
        txtHoTen1.setText("");
        txtMaDocGia1.setText("");
        txtDiaChi1.setText("");
        txtSoDT1.setText("");
        if (RdbtnNam1.isSelected()) {

            RdbtnNam1.setSelected(false);
        } else {
            RdbtnNu1.setSelected(false);
        }
//        String str1 ="";
//        try {
//            txtNgaySinh1.setDate(f.parse(str1));
//            txtngayDK1.setDate(f.parse(str1));
//            txtngayEndDK1.setDate(f.parse(str1));
//        } catch (ParseException ex) {
//            Logger.getLogger(DocGiaPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
        ShowDocGia();
    }//GEN-LAST:event_btnCapnhat1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        int row = tblDocGia1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn người muốn xóa", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            int confident = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa Độc giả này hay không!");
            if (confident == JOptionPane.YES_OPTION) {
                int dem = 0;
                String maDG = String.valueOf(tblDocGia1.getValueAt(row, 1));
                List<ThongTinMuonTra> user_ttmt = userTTMT.getAll();
                for (ThongTinMuonTra users : user_ttmt) {
                    if (users.getMaDG().equals(maDG)) {
                        if (users.getNgayTra() == null) {
                            dem++;
                        }
                    }
                }
                if (dem > 0) {
                    JOptionPane.showMessageDialog(this, "Không thể xóa Độc giả vì đang mượn sách", "Thông báo", JOptionPane.ERROR_MESSAGE);
                } else {
                    userDG.remove(maDG);
                    JOptionPane.showConfirmDialog(this, "Xóa thành công");
                    ShowDocGia();
                    txtHoTen1.setText("");
                    txtMaDocGia1.setText("");
                    txtDiaChi1.setText("");
                    txtSoDT1.setText("");
                    RdbtnNam1.setSelected(false);
                    RdbtnNu1.setSelected(false);
                }

            }

        }

    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnLuu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu1ActionPerformed
        // TODO add your handling code here:

        String ngaySinh = f.format(txtNgaySinh1.getDate());
        String ngayDK = f.format(txtngayDK1.getDate());
        String ngayEndDK = f.format(txtngayEndDK1.getDate());

        String gioitinh = "";
        if (RdbtnNam1.isSelected()) {
            gioitinh += "Nam";
        } else {
            gioitinh += "Nữ";
        }
        DocGia docGia = new DocGia();
        docGia.setMaDG(txtMaDocGia1.getText());
        docGia.setHoten(txtHoTen1.getText());
        docGia.setDiaChi(txtDiaChi1.getText());
        docGia.setGioiTinh(gioitinh);
        docGia.setSdt(txtSoDT1.getText());
        docGia.setNgaySinh(ngaySinh);
        docGia.setNgayDK(ngayDK);
        docGia.setNgayHetHan(ngayEndDK);
        userDG.update(docGia);
        JOptionPane.showConfirmDialog(this, "Thêm thành công");
        ShowDocGia();


    }//GEN-LAST:event_btnLuu1ActionPerformed

    private void btTracuu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTracuu1ActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(this, "Vui lòng nhập tên Độc giả", JOptionPane.INFORMATION_MESSAGE);

        modelDocGia.setRowCount(0);
        List<DocGia> user_DG = userDG.findByName(str);
        int sttdg = 0;
        for (DocGia users : user_DG) {
            sttdg++;
            modelDocGia.addRow(new Object[]{sttdg, users.getMaDG(), users.getHoten(), users.getGioiTinh(), users.getNgaySinh(), users.getDiaChi(), users.getSdt(), users.getNgayDK(), users.getNgayHetHan()});
        }
        if (modelDocGia.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy", "Thông báo", JOptionPane.ERROR_MESSAGE);
            ShowDocGia();
        }
    }//GEN-LAST:event_btTracuu1ActionPerformed

    private void tblDocGia1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblDocGia1AncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_tblDocGia1AncestorAdded

    private void txtHoTen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTen1ActionPerformed

    private void tblDocGia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocGia1MouseClicked
        // TODO add your handling code here:
        int row = tblDocGia1.getSelectedRow();
        txtMaDocGia1.setText(String.valueOf(tblDocGia1.getValueAt(row, 1)));
        txtHoTen1.setText(String.valueOf(tblDocGia1.getValueAt(row, 2)));
        txtSoDT1.setText(String.valueOf(tblDocGia1.getValueAt(row, 6)));
        txtDiaChi1.setText(String.valueOf(tblDocGia1.getValueAt(row, 5)));
        if (String.valueOf(tblDocGia1.getValueAt(row, 3)).equals("Nam")) {
            RdbtnNam1.setSelected(true);
        } else {
            RdbtnNu1.setSelected(true);
        }
        String ngaySinh = String.valueOf(tblDocGia1.getValueAt(row, 4));
        String ngayDK = String.valueOf(tblDocGia1.getValueAt(row, 7));
        String ngayEndDK = String.valueOf(tblDocGia1.getValueAt(row, 8));
        try {

            Date dob = f.parse(ngaySinh);
            Date NgayDK = f.parse(ngayDK);
            Date NgayendDK = f.parse(ngayEndDK);
            txtNgaySinh1.setDate(dob);
            txtngayDK1.setDate(NgayDK);
            txtngayEndDK1.setDate(NgayendDK);
        } catch (ParseException e) {
        }


    }//GEN-LAST:event_tblDocGia1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdbtnNam1;
    private javax.swing.JRadioButton RdbtnNu1;
    private javax.swing.JButton btTracuu1;
    private javax.swing.JButton btnCapnhat1;
    private javax.swing.JButton btnLuu1;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoa1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDocGia1;
    private javax.swing.JTextField txtDiaChi1;
    private javax.swing.JTextField txtHoTen1;
    private javax.swing.JLabel txtMaDocGia1;
    private com.toedter.calendar.JDateChooser txtNgaySinh1;
    private javax.swing.JTextField txtSoDT1;
    private com.toedter.calendar.JDateChooser txtngayDK1;
    private com.toedter.calendar.JDateChooser txtngayEndDK1;
    // End of variables declaration//GEN-END:variables
}
