/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.view;

import java.awt.BorderLayout;
import static java.lang.String.format;
import static java.lang.String.format;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.dao.DocGiaDao;
import main.dao.DauSachDao;
import main.dao.ThongTinMuonTraDao;
import main.dao.NhaXuatBanDao;
import main.dao.TacGiaDao;
import main.dao.TheLoaiDao;
import main.dao.TuaSachDao;
import main.model.NhaXuatBan;
import main.model.TacGia;

/**
 *
 * @author Admin
 */
public class NhaSanXuatVaTacGiaPanel extends javax.swing.JPanel {
    DefaultTableModel modelNhaSanXuat;
    DefaultTableModel modelTacGia;

    DocGiaDao userDG;
    DauSachDao userDS;
    ThongTinMuonTraDao userTTMT;
    NhaXuatBanDao userNXB;
    TacGiaDao userTG;
    TheLoaiDao userTL;
    TuaSachDao userTS;
  SimpleDateFormat f= new SimpleDateFormat("MMMM dd, yyyy"); 
    /**
     * Creates new form NSX_TagiaJPanel
     */
    public NhaSanXuatVaTacGiaPanel() {
        initComponents();
        modelNhaSanXuat = new DefaultTableModel();
        modelTacGia = new DefaultTableModel();
        userNXB = new NhaXuatBanDao();
        userTG = new TacGiaDao();
        tblNhaSanXuat4.setModel(modelNhaSanXuat);
        modelNhaSanXuat.addColumn("STT");
        modelNhaSanXuat.addColumn("Mã nhà sản xuất");
        modelNhaSanXuat.addColumn("Tên nhà sản xuất");
        ShowNSX();
        tblTacgia4.setModel(modelTacGia);
        modelTacGia.addColumn("STT");
        modelTacGia.addColumn("Mã tác giả");
        modelTacGia.addColumn("Tên tác giả");
        
        tblNhaSanXuat4.setRowHeight(40);
        tblTacgia4.setRowHeight(40);
        tblNhaSanXuat4.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblTacgia4.getColumnModel().getColumn(0).setPreferredWidth(10);
        
        ShowTacGia();
    }
    public void ShowNSX(){
        List<NhaXuatBan> user_NXB= userNXB.getAll();
        int stt = 0;
        modelNhaSanXuat.setRowCount(0);
        for (NhaXuatBan users : user_NXB) {
            stt++;
            modelNhaSanXuat.addRow(new Object[]{stt, users.getMaNXB(), users.getTenNXB()});
        }
       }
    public void ShowTacGia(){
    List<TacGia> user_TG = userTG.getAll();
        int stt = 0;
        modelTacGia.setRowCount(0);
        for (TacGia users : user_TG) {
            stt++;
            modelTacGia.addRow(new Object[]{stt, users.getMaTG(), users.getHoten()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btTracuu4_1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtTenNhaSX4 = new javax.swing.JTextField();
        btnXoa4 = new javax.swing.JButton();
        btnCapnhat4 = new javax.swing.JButton();
        btnThem4 = new javax.swing.JButton();
        btnLuu4 = new javax.swing.JButton();
        txtMaNXB4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblNhaSanXuat4 = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        btTracuu4_2 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtTenTacgia4 = new javax.swing.JTextField();
        btnXoa5 = new javax.swing.JButton();
        btnCapnhat5 = new javax.swing.JButton();
        btnThem5 = new javax.swing.JButton();
        btnLuu5 = new javax.swing.JButton();
        txtMaTacGia4 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblTacgia4 = new javax.swing.JTable();

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(0, 102, 153));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhà sản xuất"));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btTracuu4_1.setBackground(new java.awt.Color(0, 102, 153));
        btTracuu4_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTracuu4_1.setForeground(new java.awt.Color(255, 255, 255));
        btTracuu4_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/seo (2).png"))); // NOI18N
        btTracuu4_1.setText("Tra cứu");
        btTracuu4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTracuu4_1ActionPerformed(evt);
            }
        });
        jPanel13.add(btTracuu4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 31, 120, 40));

        jLabel26.setText("Mã NSX:");
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 52, 53, 28));

        jLabel27.setText("Tên nhà sản xuất:");
        jPanel13.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 107, -1, -1));
        jPanel13.add(txtTenNhaSX4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 98, 303, 34));

        btnXoa4.setBackground(new java.awt.Color(0, 102, 153));
        btnXoa4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa4.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/delete (2).png"))); // NOI18N
        btnXoa4.setText("Delete");
        btnXoa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa4ActionPerformed(evt);
            }
        });
        jPanel13.add(btnXoa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 110, 40));

        btnCapnhat4.setBackground(new java.awt.Color(0, 102, 153));
        btnCapnhat4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapnhat4.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/refresh (2).png"))); // NOI18N
        btnCapnhat4.setText("Refresh");
        btnCapnhat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhat4ActionPerformed(evt);
            }
        });
        jPanel13.add(btnCapnhat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 40));

        btnThem4.setBackground(new java.awt.Color(0, 102, 153));
        btnThem4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem4.setForeground(new java.awt.Color(255, 255, 255));
        btnThem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/add-button (1).png"))); // NOI18N
        btnThem4.setText("Add");
        btnThem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem4ActionPerformed(evt);
            }
        });
        jPanel13.add(btnThem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 110, 40));

        btnLuu4.setBackground(new java.awt.Color(0, 102, 153));
        btnLuu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu4.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/floppy-disk (1).png"))); // NOI18N
        btnLuu4.setText("Update");
        btnLuu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu4ActionPerformed(evt);
            }
        });
        jPanel13.add(btnLuu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 112, 43));
        jPanel13.add(txtMaNXB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 49, 152, 31));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 344));

        tblNhaSanXuat4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhaSanXuat4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblNhaSanXuat4);

        jPanel12.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 351, 540, 370));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin tác giả"));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btTracuu4_2.setBackground(new java.awt.Color(0, 102, 153));
        btTracuu4_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTracuu4_2.setForeground(new java.awt.Color(255, 255, 255));
        btTracuu4_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/seo (2).png"))); // NOI18N
        btTracuu4_2.setText("Tra cứu");
        btTracuu4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTracuu4_2ActionPerformed(evt);
            }
        });
        jPanel16.add(btTracuu4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 34, 120, 40));

        jLabel33.setText("Mã tác giả:");
        jPanel16.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 31, -1, 41));

        jLabel35.setText("Tên tác giả:");
        jPanel16.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 115, -1, -1));
        jPanel16.add(txtTenTacgia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 108, 365, 30));

        btnXoa5.setBackground(new java.awt.Color(0, 102, 153));
        btnXoa5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa5.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/delete (2).png"))); // NOI18N
        btnXoa5.setText("Delete");
        btnXoa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa5ActionPerformed(evt);
            }
        });
        jPanel16.add(btnXoa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 120, 40));

        btnCapnhat5.setBackground(new java.awt.Color(0, 102, 153));
        btnCapnhat5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapnhat5.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/refresh (2).png"))); // NOI18N
        btnCapnhat5.setText("Refresh");
        btnCapnhat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhat5ActionPerformed(evt);
            }
        });
        jPanel16.add(btnCapnhat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 252, 117, 41));

        btnThem5.setBackground(new java.awt.Color(0, 102, 153));
        btnThem5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem5.setForeground(new java.awt.Color(255, 255, 255));
        btnThem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/add-button (1).png"))); // NOI18N
        btnThem5.setText("Add");
        btnThem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem5ActionPerformed(evt);
            }
        });
        jPanel16.add(btnThem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 120, 40));

        btnLuu5.setBackground(new java.awt.Color(0, 102, 153));
        btnLuu5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu5.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resources/floppy-disk (1).png"))); // NOI18N
        btnLuu5.setText("Update");
        btnLuu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu5ActionPerformed(evt);
            }
        });
        jPanel16.add(btnLuu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 120, 40));
        jPanel16.add(txtMaTacGia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 31, 176, 41));

        jPanel12.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 550, 340));

        tblTacgia4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTacgia4MouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tblTacgia4);

        jPanel12.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 550, 370));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1161, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btTracuu4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTracuu4_1ActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(this,"Vui lòng nhập tên Nhà xuất bản.",JOptionPane.INFORMATION_MESSAGE);

        modelNhaSanXuat.setRowCount(0);
        List<NhaXuatBan> user_NXB = userNXB.findByName(str);
        int sttnxb = 0;
        for (NhaXuatBan users : user_NXB) {
            sttnxb++;
            modelNhaSanXuat.addRow(new Object[]{sttnxb, users.getMaNXB(), users.getTenNXB()});
        }
        if (modelNhaSanXuat.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"Không tìm thấy","Thông báo", JOptionPane.ERROR_MESSAGE );
            List<NhaXuatBan> user_NXB2 = userNXB.getAll();
           ShowTacGia();
        }
    }//GEN-LAST:event_btTracuu4_1ActionPerformed

    private void btnXoa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa4ActionPerformed
        // TODO add your handling code here:

        int row = tblNhaSanXuat4.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn Nhà xuất bản muốn xóa","Thông báo", JOptionPane.ERROR_MESSAGE );
        }else
        {
            int confident = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa Nhà xuất bản này hay không!");
            if (confident == JOptionPane.YES_OPTION) {
                String maNXB = String.valueOf(tblNhaSanXuat4.getValueAt(row, 1));
                userNXB.remove(maNXB);
                JOptionPane.showConfirmDialog(this, "Xóa nhà xuất bản thàng công");
                txtTenNhaSX4.setText("");
        txtMaNXB4.setText("");
             ShowNSX();

            }
        }

    }//GEN-LAST:event_btnXoa4ActionPerformed

    private void btnCapnhat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhat4ActionPerformed
        // TODO add your handling code here:
        txtTenNhaSX4.setText("");
        txtMaNXB4.setText("");
        ShowNSX();
    }//GEN-LAST:event_btnCapnhat4ActionPerformed

    private void btnThem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem4ActionPerformed
        // TODO add your handling code here:
        NhaXuatBan nhaXuatBan = new NhaXuatBan();
        nhaXuatBan.setTenNXB(txtTenNhaSX4.getText());
        List<NhaXuatBan> list = new ArrayList<NhaXuatBan>();
        list.add(nhaXuatBan);
        userNXB.insert(nhaXuatBan);
        JOptionPane.showConfirmDialog(this, "Thêm thành công");
        txtTenNhaSX4.setText("");
        txtMaNXB4.setText("");
        txtTenNhaSX4.setText("");
        txtMaNXB4.setText("");
        ShowNSX();
    }//GEN-LAST:event_btnThem4ActionPerformed

    private void btnLuu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu4ActionPerformed
        // TODO add your handling code here:
        NhaXuatBan nhaXuatBan = new NhaXuatBan();
        nhaXuatBan.setMaNXB(txtMaNXB4.getText());
        nhaXuatBan.setTenNXB(txtTenNhaSX4.getText());
        List<NhaXuatBan> list = new ArrayList<NhaXuatBan>();
        list.add(nhaXuatBan);
        userNXB.update(nhaXuatBan);
        JOptionPane.showConfirmDialog(this, "Cập nhật thành công");
        ShowNSX();
    }//GEN-LAST:event_btnLuu4ActionPerformed

    private void btTracuu4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTracuu4_2ActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(this,"Vui lòng nhập tên Tác giả.",JOptionPane.INFORMATION_MESSAGE);

        modelTacGia.setRowCount(0);
        List<TacGia> user_TG = userTG.findByName(str);
        int stttg = 0;
        for (TacGia users : user_TG) {
            stttg++;
            modelTacGia.addRow(new Object[]{stttg, users.getMaTG(), users.getHoten()});
        }
        if (modelTacGia.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"Không tìm thấy","Thông báo", JOptionPane.ERROR_MESSAGE );
            ShowTacGia();
        }
    }//GEN-LAST:event_btTracuu4_2ActionPerformed

    private void btnXoa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa5ActionPerformed
        // TODO add your handling code here:
        int row = tblTacgia4.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn Tác giá muốn xóa","Thông báo", JOptionPane.ERROR_MESSAGE );
        }else
        {
            int confident = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa Tác giả này hay không!");
            if (confident == JOptionPane.YES_OPTION) {
                String maTG = String.valueOf(tblTacgia4.getValueAt(row, 1));
                userTG.remove(maTG);
                JOptionPane.showConfirmDialog(this, "Xóa thành công");
                  txtMaTacGia4.setText("");
        txtTenTacgia4.setText("");
                ShowTacGia();
            }
        }
    }//GEN-LAST:event_btnXoa5ActionPerformed

    private void btnCapnhat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhat5ActionPerformed
        // TODO add your handling code here:
        txtMaTacGia4.setText("");
        txtTenTacgia4.setText("");
       ShowTacGia();
    }//GEN-LAST:event_btnCapnhat5ActionPerformed

    private void btnThem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem5ActionPerformed
        // TODO add your handling code here:
        TacGia tacGia = new TacGia();
        tacGia.setHoten(txtTenTacgia4.getText());
        List<TacGia> list = new ArrayList<TacGia>();
        list.add(tacGia);
        userTG.insert(tacGia);
        JOptionPane.showConfirmDialog(this, "Thêm thành công");
          txtMaTacGia4.setText("");
        txtTenTacgia4.setText("");
        ShowTacGia();
    }//GEN-LAST:event_btnThem5ActionPerformed

    private void btnLuu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu5ActionPerformed
        // TODO add your handling code here:
        TacGia tacGia = new TacGia();
        tacGia.setMaTG(txtMaTacGia4.getText());
        tacGia.setHoten(txtTenTacgia4.getText());
        
        userTG.update(tacGia);
        JOptionPane.showConfirmDialog(this, "Cập nhật thành công");
          txtMaTacGia4.setText("");
        txtTenTacgia4.setText("");
        ShowTacGia();
    }//GEN-LAST:event_btnLuu5ActionPerformed

    private void tblNhaSanXuat4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaSanXuat4MouseClicked
        // TODO add your handling code here:
        int row = tblNhaSanXuat4.getSelectedRow();
                txtMaNXB4.setText(String.valueOf(tblNhaSanXuat4.getValueAt(row, 1)));
                txtTenNhaSX4.setText(String.valueOf(tblNhaSanXuat4.getValueAt(row, 2)));
    }//GEN-LAST:event_tblNhaSanXuat4MouseClicked

    private void tblTacgia4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTacgia4MouseClicked
        // TODO add your handling code here:
        
        int row = tblTacgia4.getSelectedRow();
                txtMaTacGia4.setText(String.valueOf(tblTacgia4.getValueAt(row, 1)));
                txtTenTacgia4.setText(String.valueOf(tblTacgia4.getValueAt(row, 2)));
    }//GEN-LAST:event_tblTacgia4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTracuu4_1;
    private javax.swing.JButton btTracuu4_2;
    private javax.swing.JButton btnCapnhat4;
    private javax.swing.JButton btnCapnhat5;
    private javax.swing.JButton btnLuu4;
    private javax.swing.JButton btnLuu5;
    private javax.swing.JButton btnThem4;
    private javax.swing.JButton btnThem5;
    private javax.swing.JButton btnXoa4;
    private javax.swing.JButton btnXoa5;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblNhaSanXuat4;
    private javax.swing.JTable tblTacgia4;
    private javax.swing.JLabel txtMaNXB4;
    private javax.swing.JLabel txtMaTacGia4;
    private javax.swing.JTextField txtTenNhaSX4;
    private javax.swing.JTextField txtTenTacgia4;
    // End of variables declaration//GEN-END:variables
}
